on: [push]

name: 'test docker'
description: 'test building docker image'
runs:
  using: 'docker'
  image: 'Dockerfile'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: docker run
      uses: 'test docker'

